### ISSUE TITLE
Module Registration

### ISSUE THREAD

**Issue by ryantheleach** [kinggoesgaming/FoundationsAPI#1]
> [01:47:16] <kggarmy> cuz i have a module system and i want to provide a service and then plugin add modules and my plugin again makes sure all modules are loaded before next event..
>[01:47:44] <kggarmy> I suppose an early and a late would suffice

Make modules listen for module registration event, and register then, only throw module registration event after the service is ready to accept module registrations.

**Comment by kinggoesgaming** [comment]
I will be working on implementing module api part today or tomorrow and keep this in mind.

**Comment by kinggoesgaming** [comment]
Ok just checked event registration and apparently event manager allows registering events in preinit phase... contrary to what is said in the javadocs.. so I think that would most likely be happening as soon as my configuration side of things are set in kinggoesgaming/FoundationsCore, which is almost done.
